files: 
  - original: sample.txt
    summary: sample_summarized.txt
  - original: lecture9.txt
    summary: lecture9_summarized.txt
  - original: lecture8.txt
    summary: lecture8_summarized.txt
  - original: virtuallearningnotes.docx
    summary: virtuallearningnotes_summarized.docx
  - original: textreview_notes.docx
    summary: textreview_notes_summarized.docx
  - original: transcript_sample.txt
    summary: transcript_sample_summarized.txt
  - original: vietnameselang.txt
    summary: vietnameselang_summarized.txt
  - original: presentationnotes.txt
    summary: presentationnotes_summarized.txt
  - original: genderdisparities_notes.txt
    summary: genderdisparities_notes_summarized.txt
  - original: lecturenotes_sample.txt
    summary: lecturenotes_sample_summarized.txt
  - original: transcript_lec_1.txt
    summary: notes_lec_1.txt
    type: compsci
  - original: transcript_lec_2.txt
    summary: notes_lec_2.txt
    type: compsci
  - original: transcript_lec_3.txt
    summary: notes_lec_3.txt
    type: compsci
  - original: transcript_lec_4.txt
    summary: notes_lec_4.txt
    type: compsci
  - original: transcript_lec_5.txt
    summary: notes_lec_5.txt
    type: compsci
  - original: transcript_lec_6.txt
    summary: notes_lec_6.txt
    type: compsci
  - original: transcript_lec_7.txt
    summary: notes_lec_7.txt
    type: compsci
  - original: transcript_lec_8.txt
    summary: notes_lec_8.txt
    type: compsci
  - original: transcript_lec_9.txt
    summary: notes_lec_9.txt
    type: compsci
  - original: transcript_lec_10.txt
    summary: notes_lec_10.txt
    type: compsci
  - original: transcript_lec_11.txt
    summary: notes_lec_11.txt
    type: compsci
  - original: transcript_lec_12.txt
    summary: notes_lec_12.txt
    type: compsci
 
# - original: another_sample.txt
#   summary: another_sample_summarized.txt
#   type: compsci
