files: 
  - original: sample.txt
    summary: sample_summarized.txt
  - original: transcript_sample.txt
    summary: transcript_sample_summarized.txt
  - original: vietnameselang.txt
    summary: vietnameselang_summarized.txt
  - original: presentationnotes.txt
    summary: presentationnotes_summarized.txt
  - original: genderdisparities_notes.txt
    summary: genderdisparities_notes_summarized.txt
  - original: lecturenotes_sample.txt
    summary: lecturenotes_sample_summarized.txt
  
 
# - original: another_sample.txt
#   summary: another_sample_summarized.txt
#   type: compsci
