files: 
  - original: sample.txt
    summary: sample_summarized.txt
  - original: lecture9.txt
    summary: lecture9_summarized.txt
  - original: lecture8.txt
    summary: lecture8_summarized.txt
  - original: virtuallearningnotes.docx
    summary: virtuallearningnotes_summarized.docx
  - original: textreview_notes.docx
    summary: textreview_notes_summarized.docx
  - original: transcript_sample.txt
    summary: transcript_sample_summarized.txt
  - original: vietnameselang.txt
    summary: vietnameselang_summarized.txt
  - original: virtuallearningnotes.txt
    summary: virtuallearningnotes_summarized.txt
  - original: presentationnotes.txt
    summary: presentationnotes_summarized.txt
  - original: virtuallearningnotes.txt
    summary: virtuallearningnotes_summarized.txt
  # To add more files, specify the original and summary file names in the smae format:
  # - original: another_sample.txt
  #   summary: another_sample_summarized.txt
  
