files: 
  - original: sample.txt
    summary: sample_summarized.txt
  # To add more files, specify the original and summary file names in the smae format:
  # - original: another_sample.txt
  #   summary: another_sample_summarized.txt
  